services:
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - "13378:80"
    volumes:
      - ./media/Audiobooks:/audiobooks    # add ./media/Podcasts:/podcasts later
      - ./config:/config
      - ./metadata:/metadata
    restart: unless-stopped
